In [9]:
import numpy as np

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
from sklearn.linear_model import LinearRegression
# LinearRegression(copy_X = True, fit_intercept = True, normalize = True)

In [14]:
X, y = np.arange(10).reshape((5,2)), range(5)

In [15]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [16]:
list(y)

[0, 1, 2, 3, 4]

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [20]:
X_train

array([[2, 3],
       [4, 5],
       [6, 7]])

In [21]:
y_train

[1, 2, 3]

In [22]:
X_test

array([[8, 9],
       [0, 1]])

In [23]:
y_test

[4, 0]